### ISSUE TITLE
code for cifar10 prediction

### ISSUE THREAD

**Issue by smwanghhh** [WayneDW/Contour-Stochastic-Gradient-Langevin-Dynamics#1]
Can you share the code for cifa10 prediction? Thanks.

**Comment by WayneDW** [comment]
The current version is not scalable to high-loss cases and this is why we included a high-order bias in the stochastic approximation as shown in Appendix D.4, which still requires an excessively large batch size of 1000 and some tuning on the extra bias. We have worked out a variant that can work well in the case of high-losses. You can wait a while for the new version to study if you don't mind. If you are still interested in this version, you can send me your email.

**Comment by smwanghhh** [comment]
Thanks. My email is smwang1994@163.com.

**Comment by WayneDW** [comment]
> Thanks. My email is [smwang1994@163.com](mailto:smwang1994@163.com).

Sent.
